import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Read the image
im = Image.open("input.bmp")
p = np.array(im)

channel = p[:,:,0]

channel[np.where(channel == 0)] = 1
channel[np.where(channel == 255)] = 0


# compute the k
binary_str = ''  
for j in range(107):
    for i in range(16,-1,-1):
  
        
        binary_str += str(channel[i,j])
    

k = int(binary_str, 2) * 17


# Does the Tupper calc
def tupper(x,y):

    H = 17
    return 0.5 < ((y//H) // (2**(H*x + y%H))) % 2
        
# Makes the plot
out_image = np.zeros((107,17))
for y in range(k+16, k-1, -1):
    
    for x in range(1,107,1):
        if tupper(x,y):
            out_image[x,y-k] = 1
        else:
            out_image[x,y-k] = 0



plt.imshow(np.rot90(out_image,3), origin='upper')
#plt.show()

plt.xlabel('x')
plt.ylabel('y - k')
plt.savefig("test.png",bbox_inches='tight')


print "This plot was generated by plotting:"
print k

